package com.example.nextgenecommerce.data.repository

import android.util.Log
import com.example.nextgenecommerce.data.models.SupabaseReview
import com.example.nextgenecommerce.util.Resource
import io.github.jan.supabase.gotrue.Auth
import io.github.jan.supabase.postgrest.Postgrest
import io.github.jan.supabase.postgrest.query.Order
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.flow
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import javax.inject.Inject
import javax.inject.Singleton

// Only the fields that come FROM the client — id & created_at are generated by the DB
@Serializable
private data class ReviewInsert(
    @SerialName("product_id") val productId: String,
    @SerialName("user_id")    val userId: String,
    @SerialName("user_name")  val userName: String,
    val rating: Int,
    val comment: String
)

// Used only to update rating + review_count on the products row
@Serializable
data class ProductRatingUpdate(
    val rating: Double,
    @SerialName("review_count") val reviewCount: Int
)

@Singleton
class ReviewRepository @Inject constructor(
    private val auth: Auth,
    private val postgrest: Postgrest
) {
    companion object {
        private const val TAG = "ReviewRepository"
        private const val REVIEWS_TABLE  = "reviews"
        private const val PRODUCTS_TABLE = "products"
    }

    private fun cleanError(e: Exception, fallback: String): String {
        val msg = e.message ?: ""
        return when {
            msg.contains("does not exist", ignoreCase = true) ||
            msg.contains("schema cache",   ignoreCase = true) ->
                "Reviews table not set up. Run supabase_reviews_setup.sql in your Supabase dashboard."
            msg.contains("unique constraint",     ignoreCase = true) ||
            msg.contains("duplicate key",         ignoreCase = true) ->
                "You have already reviewed this product."
            msg.contains("foreign key",           ignoreCase = true) ||
            msg.contains("not present in table",  ignoreCase = true) ->
                "Product not found in the database. Try syncing from the admin panel."
            msg.contains("policy",     ignoreCase = true) ||
            msg.contains("denied",     ignoreCase = true) ||
            msg.contains("permission", ignoreCase = true) ->
                "Permission denied. Make sure you are logged in."
            msg.contains("jwt",     ignoreCase = true) ||
            msg.contains("token",   ignoreCase = true) ->
                "Session expired. Please log in again."
            msg.contains("network", ignoreCase = true) ||
            msg.contains("timeout", ignoreCase = true) ->
                "Network error. Check your internet connection."
            else -> fallback
        }
    }

    fun getReviews(productId: String): Flow<Resource<List<SupabaseReview>>> = flow {
        emit(Resource.Loading())
        try {
            val reviews = postgrest.from(REVIEWS_TABLE)
                .select {
                    filter { eq("product_id", productId) }
                    order("created_at", Order.DESCENDING)
                }
                .decodeList<SupabaseReview>()
            emit(Resource.Success(reviews))
        } catch (e: Exception) {
            Log.e(TAG, "Error fetching reviews", e)
            emit(Resource.Error(cleanError(e, "Failed to load reviews.")))
        }
    }

    fun submitReview(
        productId: String,
        userId: String,
        userName: String,
        rating: Int,
        comment: String
    ): Flow<Resource<Unit>> = flow {
        emit(Resource.Loading())
        try {
            // Only send client-owned fields; DB handles id & created_at via DEFAULT
            postgrest.from(REVIEWS_TABLE).insert(
                ReviewInsert(
                    productId = productId,
                    userId    = userId,
                    userName  = userName.ifBlank { "Anonymous" },
                    rating    = rating,
                    comment   = comment.trim()
                )
            )

            // Non-critical: update product's average rating
            try {
                val all = postgrest.from(REVIEWS_TABLE)
                    .select { filter { eq("product_id", productId) } }
                    .decodeList<SupabaseReview>()

                if (all.isNotEmpty()) {
                    val avg     = all.map { it.rating }.average()
                    val rounded = Math.round(avg * 10.0) / 10.0
                    postgrest.from(PRODUCTS_TABLE)
                        .update(ProductRatingUpdate(rating = rounded, reviewCount = all.size)) {
                            filter { eq("id", productId) }
                        }
                }
            } catch (ratingEx: Exception) {
                Log.w(TAG, "Rating update failed (review saved OK): ${ratingEx.message}")
            }

            emit(Resource.Success(Unit))
        } catch (e: Exception) {
            Log.e(TAG, "submitReview error: ${e::class.simpleName}: ${e.message}", e)
            emit(Resource.Error(cleanError(e, "Failed to submit review (${e::class.simpleName})")))
        }
    }

    fun hasUserReviewed(productId: String): Flow<Resource<Boolean>> = flow {
        emit(Resource.Loading())
        try {
            val userId = auth.currentUserOrNull()?.id ?: run {
                emit(Resource.Success(false)); return@flow
            }
            val existing = postgrest.from(REVIEWS_TABLE)
                .select {
                    filter {
                        eq("product_id", productId)
                        eq("user_id", userId)
                    }
                }
                .decodeList<SupabaseReview>()
            emit(Resource.Success(existing.isNotEmpty()))
        } catch (e: Exception) {
            emit(Resource.Success(false))
        }
    }
}
